---
title: "undervisning"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## RESULTS

```{r}
#| label: Lean mass
#| warning: false
#| message: false
#| echo: false

library(tidyverse)
library(exscidata)
library(lme4)
data("strengthvolume")
data("dxadata")

leanmass <- dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sex, include, sets, leg, lean.mass) %>%
  filter(include == "incl") %>%
  mutate(time = factor(time, levels = c("pre", "post")),
         sets = factor(sets, levels = c("single", "multiple"))) %>%
  print()

# Lagrer det nye "wide" datasettet i et eget navn
leanmass_change_wide <- leanmass %>%
# Lager to nye variabler (pre og post) med verdiene fra lean mass
  pivot_wider(names_from = time,
              values_from = lean.mass) %>% 
# lager en ny variabel med endringen i lean mass fra pre til post
  mutate(change = post - pre) %>% 
# Velger ut de relevante variablene
  select(participant, sex, sets, change) %>% 
# Lager to nye variabler (multiple og single) med verdiene fra change. Et "wide" datasett som dette passer bra til å gjøre en t-test
  pivot_wider(names_from = sets,
              values_from = change) %>% 
# Lager en ny variebel "diff" som er differansen på endingsscoren mellom multiple og single
  mutate(diff = multiple - single) %>%
print()


# Lager et nytt "long" datsaett som fungerer bra med lm
leanmass_change_long <- leanmass %>%
  pivot_wider(names_from = time,
              values_from = lean.mass) %>%
  mutate(change = post - pre) %>%
  select(participant, sex, sets, change) %>%
  print()

# Lager et nytt datasett som fungerer bra med ANCOVA
leanmass_change_wide_time <- leanmass %>%
  pivot_wider(names_from = time,
              values_from = lean.mass) %>%
  select(participant, sex, sets, pre, post) %>%
  print()
  

# Gjør en t-test med det nye "wide" datasettet på endringsscore. Alternativene er paired, equal og variation
with(leanmass_change_wide, t.test(multiple, single, var.equal = TRUE, paired = TRUE))


# Gjør en linear model (lm) test ved å bruke "wide" datasettet på endringsscore. Til denne testen trengs pakken "lme4"
lm1 <- lm(diff ~ 1, data = leanmass_change_wide)
summary(lm1)
plot(lm1)


# Mixed effects model. Denne mdellen skal forklare lean mass ut fra time, sets og forholdet mellom time og sets, hver deltaker har et eget utgangspunkt/et eget intercept, datasettet som skal brukes er leanmass
lm2 <- lmer(lean.mass ~ time + sets + time:sets + (1|participant),
            data = leanmass)
summary(lm2)
plot(lm2)

# ANCOVA
lm3 <- lm(post ~ pre + sets, data = leanmass_change_wide_time)
#Tar hensyn til at vi møter samme person to ganger, mixed model ANCOVA
lm4 <- lmer(post ~ pre + sets + (1|participant),
            data = leanmass_change_wide_time)

summary(lm3)
summary(lm4)
```



```{r}
#| label: Strength
#| warning: false
#| message: false
#| echo: false

library(tidyverse)
library(exscidata)
library(lme4)
data("strengthvolume")
data("dxadata")

str <- strengthvolume %>%
  filter(include == "incl") %>%
  mutate(time = factor(time, levels =c("pre","post"))) %>%
  print()

str %>%
  ggplot(aes(time, load, 
             group = paste(participant, sets),
             color = sets)) +
  geom_line() +
  facet_wrap(~ exercise, scales = "free")

# Lager datasettet slik at det er likt som i dxadata
str %>%
  mutate(time = if_else(time %in% c("pre", "session1"),
                        "pre", time)) %>%
  filter(time %in% c("pre", "post")) %>%
  summarise(load = mean(load, na.rm = TRUE),
            .by = c(participant,
                    sex,
                    time,
                    sets,
                    exercise,
                    leg)) %>%
  print()
```









